// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: shortener.proto

package shortenerclient

import (
	"context"

	"go-link/app/shortener/rpc/shortener"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReq     = shortener.CreateReq
	CreateResp    = shortener.CreateResp
	GetOriginReq  = shortener.GetOriginReq
	GetOriginResp = shortener.GetOriginResp

	Shortener interface {
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
		GetOrigin(ctx context.Context, in *GetOriginReq, opts ...grpc.CallOption) (*GetOriginResp, error)
	}

	defaultShortener struct {
		cli zrpc.Client
	}
)

func NewShortener(cli zrpc.Client) Shortener {
	return &defaultShortener{
		cli: cli,
	}
}

func (m *defaultShortener) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := shortener.NewShortenerClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultShortener) GetOrigin(ctx context.Context, in *GetOriginReq, opts ...grpc.CallOption) (*GetOriginResp, error) {
	client := shortener.NewShortenerClient(m.cli.Conn())
	return client.GetOrigin(ctx, in, opts...)
}
