// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateLinkReq struct {
	Url string `json:"url"`
}

type CreateLinkResp struct {
	ShortUrl string `json:"short_url"`
}

type GetLinkReq struct {
	Code string `path:"code"` // 注意这里 tag 是 path
}

type GetLinkResp struct {
	Url string `json:"url"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
	Msg   string `json:"msg"`
}
