// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: shortener.proto

package server

import (
	"context"

	"go-link/app/shortener/rpc/internal/logic"
	"go-link/app/shortener/rpc/internal/svc"
	"go-link/app/shortener/rpc/shortener"
)

type ShortenerServer struct {
	svcCtx *svc.ServiceContext
	shortener.UnimplementedShortenerServer
}

func NewShortenerServer(svcCtx *svc.ServiceContext) *ShortenerServer {
	return &ShortenerServer{
		svcCtx: svcCtx,
	}
}

func (s *ShortenerServer) Create(ctx context.Context, in *shortener.CreateReq) (*shortener.CreateResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *ShortenerServer) GetOrigin(ctx context.Context, in *shortener.GetOriginReq) (*shortener.GetOriginResp, error) {
	l := logic.NewGetOriginLogic(ctx, s.svcCtx)
	return l.GetOrigin(in)
}
